sonar.organization=amankrs21
sonar.projectKey=amankrs21_amantra-FastAPI
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/migrations/**,.venv/**

# Ignore hardcoded credential warnings in test files
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=tests/**
